helmDefaults:
  # time in seconds to wait for any individual Kubernetes operation
  # (like Jobs for hooks, and waits on pod/pvc/svc/deployment readiness)
  # (default 300)
  timeout: 600

environments:
  dev:
    values:
---
repositories:
  - name: neo4j
    url: https://helm.neo4j.com/neo4j
  - name: aws-ebs-csi-driver
    url: https://kubernetes-sigs.github.io/aws-ebs-csi-driver
---
releases:

  - name: "aws-ebs-csi-driver"
    namespace: kube-system
    chart: "aws-ebs-csi-driver/aws-ebs-csi-driver"
    version: 2.19.0

  - name: neo4j
    namespace: '{{ env "NAMESPACE" | default "dev" }}'
    chart: neo4j/neo4j-standalone
    version: 4.4.13
    installed: true
    values:
      - volumes:
          data:
#            mode: defaultStorageClass
            mode: volume
            volume:
              persistentVolumeClaim:
                claimName: volume-manual-disk-pvc

  - name: neo4j-disk
    namespace: '{{ env "NAMESPACE" | default "localstack" }}'
    chart: neo4j/neo4j-persistent-volume
    version: 5.7.0
    installed: true
    values:
      - neo4j:
          name: neo4j-disk
        data:
          driver: ebs.csi.aws.com
          reclaimPolicy: "Delete"
          createPvc: true
          createStorageClass: false
          volumeHandle: "${volumeId}"
          capacity:
            storage: 1Gi
