helmDefaults:
  # time in seconds to wait for any individual Kubernetes operation
  # (like Jobs for hooks, and waits on pod/pvc/svc/deployment readiness)
  # (default 300)
  timeout: 600

environments:
  dev:
    values:
---
repositories:
  - name: localstack-charts
    url: https://localstack.github.io/helm-charts
  - name: neo4j
    url: https://helm.neo4j.com/neo4j
---
releases:

  - name: localstack
    namespace: '{{ env "NAMESPACE" | default "localstack" }}'
    chart: localstack-charts/localstack
    version: 0.6.0
    installed: true

  - name: neo4j
    namespace: '{{ env "NAMESPACE" | default "localstack" }}'
    chart: neo4j/neo4j-standalone
    version: 4.4.13
    installed: true
    values:
      - volumes:
          data:
            mode: defaultStorageClass